$(document).ready(function(){
    $('.food-slider').slick({
        autoplay:true,
       slidesToShow:3,
       variableWidth:true,
       prevArrow:".prev-btn",
       nextArrow:".next-btn",
    })
});